;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
			'(
				electric-pair-delete-pair
				my-char-begin
				my-char-down
				my-char-end
				my-char-left
				my-char-right
				my-char-up
				my-kill-char-left
				my-kill-char-right
				my-kill-region-or-line
				my-kill-word-down
				my-symbol-down
				my-symbol-left
				my-symbol-right
				my-symbol-up
				my-word-begin
				my-word-down
				my-word-left
				my-word-right
				my-word-up
				org-self-insert-command
				org-yank
				))

(setq mc/cmds-to-run-once
			'(
				my-add-cursor-char-left
				my-add-cursor-char-right
				my-add-cursor-symbol-end
				my-add-cursor-symbol-left
				my-add-cursor-symbol-right
				my-add-cursor-word-left
				my-add-cursor-word-right
				))
